#!/bin/bash
export XDG_DATA_DIRS="@executable_path/../Resources/share:$XDG_DATA_DIRS"
export GTK_PATH="@executable_path/../Resources/lib/gtk-3.0"
export GTK_DATA_PREFIX="@executable_path/../Resources"
export GSETTINGS_SCHEMA_DIR="@executable_path/../Resources/share/glib-2.0/schemas"
exec "@executable_path/gftp-bin" "$@"

